--câu 1
CREATE USER John IDENTIFIED BY John;
ALTER USER John QUOTA 10M ON USERS;

CREATE USER Joe IDENTIFIED BY Joe;
ALTER USER Joe QUOTA 10M ON USERS;

CREATE USER Fred IDENTIFIED BY Fred;
ALTER USER Fred QUOTA 10M ON USERS;

CREATE USER Lynn IDENTIFIED BY Lynn;
ALTER USER Lynn QUOTA 10M ON USERS;

CREATE USER Amy IDENTIFIED BY Amy;
ALTER USER Amy QUOTA 10M ON USERS;

CREATE USER Beth IDENTIFIED BY Beth;
ALTER USER Beth QUOTA 10M ON USERS;

GRANT CREATE SESSION, CREATE TABLE TO John;
GRANT CREATE SESSION, CREATE TABLE TO Joe;
GRANT CREATE SESSION, CREATE TABLE TO Fred;
GRANT CREATE SESSION, CREATE TABLE TO Lynn;
GRANT CREATE SESSION, CREATE TABLE TO Amy;
GRANT CREATE SESSION, CREATE TABLE TO Beth;

--câu 2
CREATE ROLE DataEntry;
CREATE ROLE Supervisor;
CREATE ROLE Management;

GRANT DataEntry TO John;
GRANT DataEntry TO Joe;
GRANT DataEntry TO Lynn;
GRANT Supervisor TO Fred;

GRANT Management TO Amy;
GRANT Management TO Beth;

GRANT SELECT ON Attendance TO Management;

CREATE TABLE Attendance (
    ID INT PRIMARY KEY,
    Name NVARCHAR2(100)
);
GRANT SELECT ON Attendance TO Management;
GRANT INSERT, UPDATE ON Attendance TO DataEntry;
GRANT SELECT, UPDATE ON Attendance TO Supervisor;

GRANT SELECT, INSERT, UPDATE ON Attendance TO DataEntry;
SELECT PRIVILEGE, TABLE_NAME
FROM ROLE_TAB_PRIVS
WHERE ROLE = 'DATAENTRY';

GRANT SELECT, DELETE ON Attendance TO Supervisor;
SELECT PRIVILEGE, TABLE_NAME
FROM ROLE_TAB_PRIVS
WHERE ROLE = 'SUPERVISOR';

GRANT SELECT ON Attendance TO Management;
SELECT PRIVILEGE, TABLE_NAME
FROM ROLE_TAB_PRIVS
WHERE ROLE = 'MANAGEMENT';

--câu 3
CREATE USER NameManager IDENTIFIED BY pc123;
GRANT UPDATE (Name) ON Attendance TO NameManager;

--câu 4
SELECT *
FROM DBA_TAB_PRIVS
WHERE PRIVILEGE LIKE '%CONTEXT%';

SELECT GRANTEE
FROM DBA_ROLE_PRIVS
WHERE GRANTED_ROLE = 'SELECT ANY TABLE';

--câu 5
ALTER USER DataEntry IDENTIFIED BY mgt;
GRANT GRANT ANY PRIVILEGE TO John;


SELECT PRIVILEGE, TABLE_NAME
FROM DBA_TAB_PRIVS
WHERE GRANTEE = 'JOHN';
GRANT SELECT, UPDATE ON Attendance TO Beth;

--câu 6
--?o?n mã trên s? g?p l?i khi th?c hi?n câu l?nh GRANT select ON Attendance TO sinhvien WITH GRANT OPTION.
--L?i s? x?y ra trong tr??ng h?p user giaovien không có quy?n c?p quy?n cho các role.
--Lý do chính là WITH GRANT OPTION cho phép ng??i nh?n quy?n (trong tr??ng h?p này là role sinhvien)
--c?p quy?n này cho các user khác. Nh?ng ?? s? d?ng WITH GRANT OPTION, user giaovien c?n ph?i có quy?n t??ng ?ng.
